#!/bin/sh /etc/rc.common

# LED Settings Daemon
# Run after system starts but before the trimUI OS
# For more information on how daemons work on Trimui devices, 
# see /etc/rc.common usage, and /etc/init.d for examples.
START=98
STOP=99
start() {
    printf "Starting LED SETTINGS DAEMON...\n"
    ./etc/led_controller/settings-daemon.sh
    echo "done"
}

stop_() {
    printf "Stopping LED SETTINGS DAEMON"
    killall led-settings-daemon
}