name: Makefile CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure test environment
      run: sudo make deps

    - name: Make project
      run: sudo make

    - name: Package project
      run: sudo make package
